### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by qinduanyinghua** [TexasInstruments/edgeai-modelzoo#3]
Hi, would you upload pretrained models based on cityscapes dataset?

**Comment by mathmanu** [comment]
Currently we are not planning that. Segmentation models can typically be trained quickly (compared to COCO-Detection/ImageNet-Classification models which take several days to train). So, try it and let us know if you face any issue.

**Comment by mathmanu** [comment]
But we have pretrained models based on COCO segmentation dataset. https://github.com/TexasInstruments/edgeai-modelzoo/tree/master/models/vision/segmentation/cocoseg21

That is what torchvision also has: https://pytorch.org/vision/stable/models.html#semantic-segmentation

Let us know if any model that you are interested in is missing.

**Comment by qinduanyinghua** [comment]
> But we have pretrained models based on COCO segmentation dataset. https://github.com/TexasInstruments/edgeai-modelzoo/tree/master/models/vision/segmentation/cocoseg21
> 
> That is what torchvision also has: https://pytorch.org/vision/stable/models.html#semantic-segmentation
> 
> Let us know if any model that you are interested in is missing.

ok, thanks
